const RIDDLES_1 = {
  'Riddle-1': {
    riddle: 'Mr. and Mrs. Doe have six daughters and each daughter has one brother. How many people are in the Doe family?',
    translate: 'У мистера и миссис Доу есть шесть дочерей, и у каждой дочери есть один брат. Сколько человек в семье Доу?',
    answer: 'nine',
    options: ['fourteen', 'nine', 'twelve', 'eight'],
    explain: 'There are nine Mustards in the family. Since each daughter shares the same brother, there are six girls, one boy and Mr. and Mrs. Mustard.',
    id: 1,
  },
  'Riddle-2': {
    riddle: 'David\'s father has three sons: Snap, Crackle, and _____?',
    translate: 'У отца Дэвида трое сыновей: Снайп, Крэкл и _____?',
    answer: 'David',
    options: ['Carl', 'David', 'Snap', 'Crackle'],
    explain: 'David',
    id: 2,
  },
  'Riddle-3': {
    riddle: 'What belongs to you, but other people use it more than you?',
    translate: 'Что принадлежит вам, но окружающие люди используют это чаще вас?',
    answer: 'name',
    options: ['name', 'kindness', 'pen', 'car'],
    explain: 'name',
    id: 3,
  },
  'Riddle-4': {
    riddle: 'There is an ancient invention, still used in some parts of the world today, that allows people to see through walls. What is it?',
    translate: 'Древнее изобретение, которое позволяет людям видеть сквозь стены. Используется в некоторых частях мира до сих пор. Что это?',
    answer: 'window',
    options: ['magic', 'hammer', 'window', 'superglasses'],
    explain: 'window',
    id: 4,
  },
  'Riddle-5': {
    riddle: 'You walk into a room that contains a match, a kerosene lamp, a candle and a fireplace. What would you light first?',
    translate: 'Вы входите в комнату, в которой есть спичка, керосиновая лампа, свеча и камин. Что бы вы зажгли в первую очередь?',
    answer: 'match',
    options: ['lamp', 'fireplace', 'match', 'candle'],
    explain: 'match',
    id: 5,
  },
  'Riddle-6': {
    riddle: 'What can’t talk but will reply when spoken to?',
    translate: 'Что не может говорить, но ответит, когда с ним разговаривают?',
    answer: 'echo',
    options: ['echo', 'ghost', 'carrot', 'wind'],
    explain: 'echo',
    id: 6,
  },
  'Riddle-7': {
    riddle: 'What has many needles, but doesn’t sew?',
    translate: 'У чего много иголок, но не шьет?',
    answer: 'cactus',
    options: ['cactus', 'sewing machine', 'cold', 'tailor'],
    explain: 'cactus',
    id: 7,
  },
  'Riddle-8': {
    riddle: 'If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?',
    translate: 'Если ты уронишь меня, я обязательно сломаюсь, но дай мне улыбку, и я всегда буду улыбаться в ответ. Что это?',
    answer: 'mirror',
    options: ['bush', 'mirror', 'brush', 'cup'],
    explain: 'mirror',
    id: 8,
  },
  'Riddle-9': {
    riddle: 'You will throw me away when you want to use me. You will take me in when you don’t want to use me. What am I?',
    translate: 'Вы выбросите меня, когда захотите меня использовать. Вы заберёте меня обратно, когда я стану не нужен. Что это?',
    answer: 'anchor',
    options: ['rubbish', 'anchor', 'money', 'time'],
    explain: 'anchor',
    id: 9,
  },
  'Riddle-10': {
    riddle: 'A house of wood in a hidden place. Built without nails or glue. High above the ground.',
    translate: 'Дом из дерева в скрытом месте. Построен без гвоздей и клея. Высоко над землей.',
    answer: 'nest',
    options: ['nest', 'tree', 'house', 'anthill'],
    explain: 'nest',
    id: 10,
  },
  'Riddle-11': {
    riddle: 'Break it and it gets better. Immideatly set and harder to break again.',
    translate: 'Побей его, и он станет ещё сильнее. Немедленно восстанавливается и в следующем раунде побить его становится сложнее.',
    answer: 'record',
    options: ['enemy', 'classmate', 'record', 'neighbour'],
    explain: 'record',
    id: 11,
  },
  'Riddle-12': {
    riddle: 'Creeping on its belly, curled into a ring. Eyes forever open, beware its lethal sting.',
    translate: 'Ползает на животе, сворачивается в кольцо. Глаза всегда открыты, остерегайтесь его смертельного укуса.',
    answer: 'snake',
    options: ['snake', 'spider', 'lizard', 'caterpillar'],
    explain: 'snake',
    id: 12,
  },
  'Riddle-13': {
    riddle: 'I work when I play and play when I work.',
    translate: 'Я работаю, когда играю, и играю, когда работаю.',
    answer: 'musician',
    options: ['musician', 'firefighter', 'lawyer', 'loader'],
    explain: 'musician',
    id: 13,
  },
  'Riddle-14': {
    riddle: 'I\'ll dial the proper number, and soon hear the voice of my very best friend.',
    translate: 'Я наберу нужный номер и скоро услышу голос моего самого лучшего друга.',
    answer: 'telephone',
    options: ['telephone', 'telepathy', 'telekinesis', 'television'],
    explain: 'telephone',
    id: 14,
  },
  'Riddle-15': {
    riddle: 'My sharp steel teeth, in any wood, for cutting trees are very good. So if you want to fell a tree, you\'ll have to make good use of me.',
    translate: 'Мои острые стальные зубы, в любом лесу, для рубки деревьев очень хороши. Так что, если вы хотите свалить дерево, вам придется использовать меня.',
    answer: 'saw',
    options: ['hatchet', 'saw', 'axe', 'chain'],
    explain: 'saw',
    id: 15,
  },
};

const RIDDLES_2 = {
  'Riddle-16': {
    riddle: 'I move without wings, between silken strings, I leave as you find, my substance. What am I?',
    translate: 'Я передвигаюсь без крыльев, между шелковыми нитями. Я исчезаю, как когда вы находите мои следы. Что это?',
    answer: 'spider',
    options: ['snake', 'fly', 'spider', 'bug'],
    explain: 'spider',
    id: 16,
  },
  'Riddle-17': {
    riddle: 'What is at the end of a rainbow?',
    translate: 'Что находится в конце радуги?',
    answer: 'w',
    options: ['leprechauns', 'w', 'trolls', 'gold'],
    explain: 'w',
    id: 17,
  },
  'Riddle-18': {
    riddle: 'What word has kst in the middle, in the beginning, and at the end?',
    translate: 'Какое слово имеет kst в середине, in начале и and конце?',
    answer: 'inkstand',
    options: ['instance', 'inside', 'inkstand', 'insurance'],
    explain: 'inkstand',
    id: 18,
  },
  'Riddle-19': {
    riddle: 'Without a tongue, without an ear, I can speak, and sing, and hear.',
    translate: 'Без языка и без уха, но могу говорить, петь и слышать.',
    answer: 'recorder',
    options: ['recorder', 'men', 'parrot', 'wind'],
    explain: 'recorder',
    id: 19,
  },
  'Riddle-20': {
    riddle: 'Have a look at this fine steed. He looks very strange, indeed: eats petrol, and never grazes, fast along the road he races.',
    translate: 'Посмотрите на этого прекрасного коня. Действительно, он выглядит очень странно: ест бензин и никогда не пасется, быстро мчиться по дороге.',
    answer: 'car',
    options: ['fly', 'car', 'bicycle', 'rocket'],
    explain: 'car',
    id: 20,
  },
  'Riddle-21': {
    riddle: 'This house on wheels is running a race, talking people from place to place.',
    translate: 'Этот дом на колесах мчиться по шоссе, перемещая людей с места на место.',
    answer: 'bus',
    options: ['bird', 'bus', 'fly', 'wind'],
    explain: 'bus',
    id: 22,
  },
  'Riddle-22': {
    riddle: 'I\'ve whiskers, I\'m frisky. Whisk, little mice, lest I should catch you! Please stroke my back, I\'ll purr and won\'t scratch you.',
    translate: 'У меня есть усы, я резвый. Прячтесь, маленькие мышки, чтобы я не поймал вас! Пожалуйста, погладь меня по спине, я буду мурлыкать и не буду царапаться.',
    answer: 'cat',
    options: ['dog', 'rat', 'cat', 'bat'],
    explain: 'cat',
    id: 22,
  },
  'Riddle-23': {
    riddle: 'Brother left, and right, his brother, hardly ever see each other. Mirrors is the only place where they\'re coming face to face.',
    translate: 'Брат слева, брат справа, но никогда не видятся наяву. Отражение - единственное место, где они встречаются лицом к лицу.',
    answer: 'eyes',
    options: ['eyes', 'twins', 'trees', 'minds'],
    explain: 'eyes',
    id: 23,
  },
  'Riddle-24': {
    riddle: 'Who is that with a neck and no head, two arms and no hands?  What is it?',
    translate: 'C шеей и без головы, с двумя плечами и без рук? Что это?',
    answer: 'shirt',
    options: ['scarecrow', 'stick', 'tree', 'shirt'],
    explain: 'shirt',
    id: 24,
  },
  'Riddle-25': {
    riddle: 'The more you take, the more you leave behind. What am I?',
    translate: 'Чем больше вы сделаете, тем больше останется позади вас. Что это?',
    answer: 'footsteps',
    options: ['footsteps', 'experience', 'time', 'work'],
    explain: 'footsteps',
    id: 25,
  },
  'Riddle-26': {
    riddle: 'I am not alive, but I grow; I don\'t have lungs, but I need air; I don\'t have a mouth, but water kills me. What am I?',
    translate: 'Я не живой, но я расту; У меня нет легких, но мне нужен воздух; У меня нет рта, но вода убивает меня. Что это?',
    answer: 'fire',
    options: ['ghost', 'lightning', 'dark', 'fire'],
    explain: 'fire',
    id: 26,
  },
  'Riddle-27': {
    riddle: 'I make two people out of one. What am I?',
    translate: 'Я делаю двух человек из одного. Что я?',
    answer: 'mirror',
    options: ['mirror', 'physics', 'science', 'magic'],
    explain: 'mirror',
    id: 27,
  },
  'Riddle-28': {
    riddle: 'What goes up but never comes down?',
    translate: 'Что всегда увеличивается, но никогда не уменьшится?',
    answer: 'age',
    options: ['salary', 'experience', 'speed of light', 'age'],
    explain: 'age',
    id: 28,
  },
  'Riddle-29': {
    riddle: 'If you have me, you want to share me. If you share me, you haven\'t got me. What am I?',
    translate: 'Если у вас есть это, вы хотите поделиться этим. Если вы поделитесь этим, вы навсегда это потеряете. Что это?',
    answer: 'secret',
    options: ['secret', 'cigarettes', 'money', 'advice'],
    explain: 'secret',
    id: 29,
  },
  'Riddle-30': {
    riddle: 'If you look at the number on my face you won\'t find thirteen anyplace.',
    translate: 'Если вы посмотрите на число на моем лице, вы нигде не найдете тринадцать.',
    answer: 'clock',
    options: ['youth', 'ground', 'clock', 'mirrow'],
    explain: 'clock',
    id: 30,
  },
};

const RIDDLES_3 = {
  'Riddle-31': {
    riddle: 'Which word in the dictionary is spelled incorrectly?',
    translate: 'Какое слово в словаре записано неправильно?',
    answer: 'incorrectly',
    options: ['gobbledygook', 'incorrectly', 'correctly', 'dictionary'],
    explain: 'incorrectly',
    id: 31,
  },
  'Riddle-32': {
    riddle: 'He makes nets and what\'s more never fishes.',
    translate: 'Он делает сети и, более того, никогда не ловит рыбу.',
    answer: 'spider',
    options: ['cat', 'grandfather', 'snake', 'spider'],
    explain: 'spider',
    id: 32,
  },
  'Riddle-33': {
    riddle: 'A box without hinges, key, or lid, Yet golden treasure inside is hid.',
    translate: 'Коробка без петель, ключа или крышки, c золотым сокровищем внутри.',
    answer: 'egg',
    options: ['bottle', 'egg', 'chest', 'case'],
    explain: 'egg',
    id: 33,
  },
  'Riddle-34': {
    riddle: 'A thousand spades, and shovels, too, can never do what I can do.',
    translate: 'Тысяча лопат и шуфелей никогда не смогут сделать то, что я могу сделать.',
    answer: 'excavator',
    options: ['water', 'wind', 'fire', 'excavator'],
    explain: 'excavator',
    id: 34,
  },
  'Riddle-35': {
    riddle: 'Early at dawn he\'s the first to awake, and a terrible sound he\'s ready to make. This shrill, alarming, deafening sound arouses from sleep everybody around. In the distance this sound dies away, ushering in another new day.',
    translate: 'Рано на рассвете он проснулся первым, и он готов издать ужасный звук. Этот пронзительный, тревожный, оглушительный звук пробуждает сон у всех вокруг. Вдали этот звук гаснет, открывая еще один новый день.',
    answer: 'rooster',
    options: ['alarm clock', 'rooster', 'sun', 'sunset'],
    explain: 'rooster',
    id: 35,
  },
  'Riddle-36': {
    riddle: 'This wingless bird will soar, and soon land quite safely On the Moon',
    translate: 'Эта бескрылая птица взлетит и скоро благополучно приземлится на Луну',
    answer: 'rocket',
    options: ['crow', 'rocket', 'bullet', 'mind'],
    explain: 'rocket',
    id: 36,
  },
  'Riddle-37': {
    riddle: 'Which month of the year has 28 days?',
    translate: 'В каком месяце года 28 дней?',
    answer: 'all',
    options: ['April', 'all', 'September', 'May'],
    explain: 'all',
    id: 37,
  },
  'Riddle-38': {
    riddle: 'What can you break, even if you never pick it up or touch it?',
    translate: 'Что вы можете разрушить, без прикосновений к чему-либо или взаимодействий с кем-либо?',
    answer: 'promise',
    options: ['air', 'smile', 'promise', 'building'],
    explain: 'promise',
    id: 38,
  },
  'Riddle-39': {
    riddle: 'I have no feet, no hands, no wings, but I climb to the sky. What am I?',
    translate: 'У меня нет ни ног, ни рук, ни крыльев, но я поднимаюсь в небо. Что это?',
    answer: 'smoke',
    options: ['bird', 'smoke', 'rain', 'fog'],
    explain: 'smoke',
    id: 39,
  },
  'Riddle-40': {
    riddle: 'When you do not know what I am, then I am something. When you know what I am, then I am nothing. What am I?',
    translate: 'Я рожден от воды и умираю, когда возращаюсь к состоянию рождения. Что это?',
    answer: 'ice',
    options: ['ground', 'wind', 'ice', 'dew'],
    explain: 'ice',
    id: 40,
  },
  'Riddle-41': {
    riddle: 'I’m light as a feather, yet the strongest person can’t hold me for ten minutes. What am I?',
    translate: 'Я легок, как перышко, но самый сильный человек не может удержать меня десять минут. Что я?',
    answer: 'breath',
    options: ['feather', 'breath', 'mouse', 'fly'],
    explain: 'breath',
    id: 41,
  },
  'Riddle-42': {
    riddle: 'What has many teeth, but can’t bite?',
    translate: 'Много зубов, но не кусается?',
    answer: 'comb',
    options: ['shark', 'human', 'comb', 'spider'],
    explain: 'comb',
    id: 42,
  },
  'Riddle-43': {
    riddle: 'What is 3/7 chicken, 2/3 cat and 2/4 goat?',
    translate: 'Что получится из 3/7 курицы, 2/3 кошки и 2/4 козы?',
    answer: 'Chicago',
    options: ['Chicago', 'Michigan', 'China', 'Chicagao'],
    explain: 'Rebus',
    id: 43,
  },
  'Riddle-44': {
    riddle: 'What can fill a room but takes up no space?',
    translate: 'Что может заполнить комнату, но не занимает места?',
    answer: 'light',
    options: ['furniture', 'people', 'things', 'light'],
    explain: 'light',
    id: 44,
  },
  'Riddle-45': {
    riddle: 'Squeeze it and it cries tears as red as it\'s body. It\'s heart is made of stone.',
    translate: 'Сожмите это, и оно заплачет красными слезами,такими же красными, как и его тело. Это сердце сделано из камня.',
    answer: 'cherry',
    options: ['watermelon', 'apple', 'cherry', 'plum'],
    explain: 'cherry',
    id: 45,
  },
  'Riddle-46': {
    riddle: 'Mary has four daughters, and each of her daughters has a brother. How many children does Mary have?',
    translate: 'У Марии четыре дочери, и у каждой из ее дочерей есть брат. Сколько детей у Мэри?',
    answer: 'five',
    options: ['eight', 'four', 'five', 'six'],
    explain: 'Five — each daughter has the same brother.',
    id: 46,
  },
};

const RIDDLES_4 = {
  'Riddle-46': {
    riddle: 'Look at me in some moment. I can bring a smile to your face, A tear to your eye, Or even a thought to your mind. But, I can\'t be seen. What am I?',
    translate: 'Посмотри на меня в любой момент. Я могу вызвать улыбку на твоем лице, слёзы в твоих глазах или любую другую мысль. Но меня не видно. Что это?',
    answer: 'memories',
    options: ['sunrise', 'tv', 'memories', 'sunset'],
    explain: 'memories',
    id: 46,
  },
  'Riddle-47': {
    riddle: 'Each dot on this ladder looks like a bird. They\'re all singing songs that I\'ve never heard.',
    translate: 'Каждая точка на этой лестнице выглядит как птица. Они все поют песни, которые я никогда не слышал.',
    answer: 'notes',
    options: ['birds', 'notes', 'keys', 'leaves'],
    explain: 'notes',
    id: 47,
  },
  'Riddle-48': {
    riddle: 'The black bird spread its wings. Under their canopy lay the wide world, sleeping sound, till the break of next day.',
    translate: 'Черная птица расправила крылья. Под их навесом пролежит широкий мир и спящий звук до рассвета следующего дня.',
    answer: 'night',
    options: ['storm', 'rain', 'day', 'night'],
    explain: 'night',
    id: 48,
  },
  'Riddle-49': {
    riddle: `Always in you, Sometimes on you;
    If I surround you, I can kill you.
    What am I?`,
    translate: 'Всегда в тебе, иногда на тебе. Eсли погрузишься в неё с головой, то можешь этого не пережить. Что это?',
    answer: 'water',
    options: ['bacteria', 'ground', 'love', 'water'],
    explain: 'water',
    id: 49,
  },
  'Riddle-50': {
    riddle: 'What goes through cities and fields, but never moves?',
    translate: 'Что проходит через города и поля, но никогда не движется?',
    answer: 'road',
    options: ['mouse', 'car', 'bird', 'road'],
    explain: 'road',
    id: 50,
  },
  'Riddle-51': {
    riddle: 'What has a neck but no head?',
    translate: 'У чего есть шея, но нет головы?',
    answer: 'bottle',
    options: ['bottle', 'ghost', 'tree', 'dove'],
    explain: 'bottle',
    id: 51,
  },
  'Riddle-52': {
    riddle: 'I do not have wings, but I can fly. I don’t have eyes, but I can cry. What am I?',
    translate: 'У меня нет крыльев, но я умею летать. У меня нет глаз, но я могу плакать. Что это?',
    answer: 'cloud',
    options: ['cloud', 'fog', 'ground', 'ocean'],
    explain: 'cloud',
    id: 52,
  },
  'Riddle-53': {
    riddle: 'People buy me to eat, but never eat me. What am I?',
    translate: 'Люди покупают меня, чтобы поесть, но никогда не едят меня. Что я?',
    answer: 'plate',
    options: ['vegetables', 'soap', 'plate', 'candy'],
    explain: 'plate',
    id: 53,
  },
  'Riddle-54': {
    riddle: 'I am born of water but when I return to water, I die. What am I?',
    translate: 'Я рожден от воды и умираю, когда возращаюсь к состоянию рождения. Что это?',
    answer: 'ice',
    options: ['ground', 'wind', 'ice', 'dew'],
    explain: 'ice',
    id: 54,
  },
  'Riddle-55': {
    riddle: 'I know a thousand faces, of many who have died. Wielding well a mighty power. Masses fall upon their knees, to scarce behold my only side.',
    translate: 'Я знаю тысячу лиц и многие уже мертвы. Обладаю могущественной силой. Массы падают на колени, чтобы едва увидеть мою единственную сторону.',
    answer: 'coin',
    options: ['photo', 'ground', 'money', 'coin'],
    explain: 'coin',
    id: 55,
  },
  'Riddle-56': {
    riddle: 'I am the outstretched fingers that seize and hold the wind. Wisdom flows from me in other hands. My merest touch brings laughter. What am I?',
    translate: 'Я - вытянутые пальцы, которые захватывают и удерживают ветер. Мудрость течет от меня в другие руки. Мое простое прикосновение приносит смех. Что это?',
    answer: 'feather',
    options: ['finger', 'pen', 'feather', 'hand'],
    explain: 'feather',
    id: 56,
  },
  'Riddle-57': {
    riddle: 'Take off my skin - I won\'t cry, but you will! What am I?',
    translate: 'Сними мою кожу - я не буду плакать, а ты будешь! Что это?',
    answer: 'onion',
    options: ['garlic ', 'onion', 'pepper', 'melon'],
    explain: 'onion',
    id: 57,
  },
  'Riddle-58': {
    riddle: 'What kind of room has no windows or doors?',
    translate: 'В какой комнате нет окон или дверей?',
    answer: 'mushroom',
    options: ['kitchen ', 'bedroom', 'mushroom', 'hall'],
    explain: 'MUSHroom',
    id: 58,
  },
  'Riddle-59': {
    riddle: 'It can poison water in a way no detect poison can tell you. Damned it is in water, highly priced when dry.',
    translate: 'Это делает воду непригодной для питья. Не востребовано в жидкости, высоко ценится в сухом виде.',
    answer: 'salt',
    options: ['salt', 'sugar', 'sand', 'pepper'],
    explain: 'salt',
    id: 59,
  },
  'Riddle-60': {
    riddle: 'The Pearls of night, stolen in clearest light of day.',
    translate: 'Жемчужины ночи, украденные при ярком свете дня.',
    answer: 'dew',
    options: ['dew', 'grass', 'Moon', 'darkness'],
    explain: 'dew',
    id: 60,
  },
};

const RIDDLES_5 = {
  'Riddle-61': {
    riddle: 'I soar without wings, I see without eyes. I\'ve traveled the universe to and fro. I\'ve conquered the world, yet I\'ve never been anywhere but home. Who am I?',
    translate: 'Я парю без крыльев, вижу без глаз. Я путешествовал по вселенной взад и вперед. Я покорил мир, но никогда не был нигде, кроме дома. Что это?',
    answer: 'imagination',
    options: ['rocket', 'bird', 'wind', 'imagination'],
    explain: 'imagination',
    id: 61,
  },
  'Riddle-62': {
    riddle: `Voiceless it cries,
    Wingless flutters,
    Toothless bites,
    Mouthless mutters.`,
    translate: `Безмолвно плачет,
    Бескрыло порхает,
    Беззубо кусает,
    Бестолково бормочет.`,
    answer: 'wind',
    options: ['grandfather', 'spider', 'rain', 'wind'],
    explain: 'wind',
    id: 62,
  },
  'Riddle-63': {
    riddle: 'If eleven plus two equals one, what does nine plus five equal?',
    translate: 'Если одиннадцать плюс два равно единица, то чему равняется девять плюс пять?',
    answer: 'two',
    options: ['three', 'fourteen', 'two', 'four'],
    explain: '11 o\'clock plus 2 hours = 1 o\'clock. 9 o\'clock plus 5 hours = 2 o\'clock',
    id: 63,
  },
  'Riddle-64': {
    riddle: 'I shave every day, but my beard stays the same. What am I?',
    translate: 'Если у вас есть это, вы хотите поделиться этим. Если вы поделитесь этим, вы навсегда это потеряете. Что это?',
    answer: 'barber',
    options: ['pirate', 'soldier', 'grandfather', 'barber'],
    explain: 'barber',
    id: 64,
  },
  'Riddle-65': {
    riddle: 'It is running night and day, but it never runs away.',
    translate: 'Идут днем и ночью, но никогда не придут.',
    answer: 'watch',
    options: ['watch', 'sprinter', 'car', 'steps'],
    explain: 'watch',
    id: 65,
  },
  'Riddle-66': {
    riddle: 'What is always in front of you but can’t be seen?',
    translate: 'Что всегда перед тобой, но не видно?',
    answer: 'future',
    options: ['happiness', 'future', 'lie', 'nose'],
    explain: 'future',
    id: 66,
  },
  'Riddle-67': {
    riddle: 'What five-letter word becomes shorter when you add two letters to it?',
    translate: 'Какое пятибуквенное слово становится короче, когда вы добавляете к нему две буквы?',
    answer: 'short',
    options: ['early', 'earlier', 'shorter', 'short'],
    explain: 'short',
    id: 67,
  },
  'Riddle-68': {
    riddle: 'A warrior amongst the flowers, He bears a thrusting sword. Able and ready to use, To guard his golden hoard.',
    translate: 'Воин среди цветов, у которого при себе меч. Способный и готовый к использованию, чтобы охранять его золотой запас.',
    answer: 'bee',
    options: ['pirate', 'knight', 'bee', 'ant'],
    explain: 'bee',
    id: 68,
  },
  'Riddle-69': {
    riddle: 'I reflect the light, thats not very bright, I sit in the same place all year, all the time. Right here, you cannot see me all right, at least when its not night.',
    translate: 'Я отражаю свет, который не очень яркий, я сижу в одном и том же месте весь год, все время. Прямо здесь, вы не можете видеть меня хорошо, по крайней мере, если сейчас не ночь.',
    answer: 'Moon',
    options: ['Sun', 'Moon', 'light', 'mirror'],
    explain: 'Moon',
    id: 69,
  },
  'Riddle-70': {
    riddle: 'What is inanimate, yet can stand up. Can start out copper and end up as steel. So fragile, a child could break one. But many have the strength to lift a man? What is it?',
    translate: 'Что неодушевленно, но может встать. Может быть цвета меди или в конечном итоге цвета стали. Tаким хрупким, что ребенок может сломать его. Но у многих есть силы, чтобы поднять человека? Что это?',
    answer: 'hair',
    options: ['hair', 'spirit', 'crane', 'levitation'],
    explain: 'hair',
    id: 70,
  },
  'Riddle-71': {
    riddle: 'I can’t be bought, but I can be stolen with a glance. I’m worthless to one, but priceless to two. What am I?',
    translate: 'Меня нельзя купить, но я могу быть украдена с первого взгляда. Я бесполезен для одного, но бесценен для двух. Что я?',
    answer: 'love',
    options: ['fear', 'anger', 'laughter', 'love'],
    explain: 'love',
    id: 71,
  },
  'Riddle-72': {
    riddle: 'Look at me in some moment. I can bring a smile to your face, A tear to your eye, Or even a thought to your mind. But, I can\'t be seen. What am I?',
    translate: 'Посмотри на меня в любой момент. Я могу вызвать улыбку на твоем лице, слёзы в твоих глазах или любую другую мысль. Но я никогда не буду увидена вновь наяву. Что это?',
    answer: 'memories',
    options: ['sunrise', 'tv', 'memories', 'sunset'],
    explain: 'memories',
    id: 72,
  },
  'Riddle-73': {
    riddle: 'The root tops the trunk on this backward thing, that grows in the winter and dies in the spring.',
    translate: 'Корка покрывает ствол этой вещи, которая растет зимой и умирает весной.',
    answer: 'icicle',
    options: ['ice', 'stick', 'icicle', 'winter'],
    explain: 'icicle',
    id: 73,
  },
  'Riddle-74': {
    riddle: 'My name is Tom, I live on a farm. There are four other dogs on the farm with me. Their names are Dash, Flash, Speedy and Storm. What do you think the fifth dog’s name is?',
    translate: 'Меня зовут Том, я живу на ферме. Со мной на ферме еще четыре собаки. Их зовут Dash, Flash, Speedy и Storm. Как вы думаете, пятую собаку зовут?',
    answer: 'Tom',
    options: ['Brucy', 'Jack', 'Billy', 'Tom'],
    explain: 'Tom',
    id: 74,
  },
  'Riddle-75': {
    riddle: 'After you go through a fall I will take over. All life will stall, or at least grow slower. What am I?',
    translate: 'После того, как пройдёте через осень, я верну свои права. После этого вся жизнь замрёт или будет расти медленнее. Что это?',
    answer: 'winter',
    options: ['winter', 'time', 'dark', 'sleep'],
    explain: 'winter',
    id: 75,
  },
};

const RIDDLES_6 = {
  'Riddle-76': {
    riddle: 'What 4-letter word can be written forward, backward or upside down, and can still be read from left to right?',
    translate: 'Какое 4-буквенное слово может быть написано вперед, назад или вверх ногами, и все еще может читаться слева направо?',
    answer: 'NONE',
    options: ['HOME', 'ROME', 'NOON', 'BONE'],
    explain: 'NONE',
    id: 76,
  },
  'Riddle-77': {
    riddle: 'What common English verb becomes its own past tense by rearranging its letters?',
    translate: 'Какой неправильный английский глагол становится собственным прошедшим временем при перестановке букв?',
    answer: 'eat',
    options: ['read', 'hold', 'beat', 'eat'],
    explain: 'eat -> ate',
    id: 77,
  },
  'Riddle-78': {
    riddle: 'They have not flesh, nor feathers, nor scales, nor bone. Yet they have fingers and thumbs of their own. What are they?',
    translate: 'У них нет ни плоти, ни перьев, ни чешуи, ни костей. И все же у них есть свои пальцы. Что это?',
    answer: 'gloves',
    options: ['frogs', 'shoes', 'cold', 'gloves'],
    explain: 'gloves',
    id: 78,
  },
  'Riddle-79': {
    riddle: 'I\'m as small as an ant, as big as a whale. I\'ll approach like a breeze, but can come like a gale. By some I get hit, but all have shown fear. I\'ll dance to the music, though I can\'t hear. Of names I have many, of names I have one. I\'m as slow as a snail, but from me you can\'t run. What am I?',
    translate: 'Бываю такой же маленькой, как муравей, бываю такой же большой, как кит. Я подкрадусь медленно, как штиль, но могу появиться молниеносно, как шторм. От некоторых я получаю удары, но многим внушала страх. Я буду танцевать под музыку, хотя ничего не слышу слышу. Много имён, но суть одна. Я медленна, как улитка, но от меня ты не сможешь убежать. Что это?',
    answer: 'shadow',
    options: ['fear', 'wind', 'sprinter', 'shadow'],
    explain: 'shadow',
    id: 79,
  },
  'Riddle-80': {
    riddle: 'I am an odd number. Take away a letter and I become even. What number am I?',
    translate: 'Я нечётная цифра. Уберите одну букву и эта цифра станет чётной. О какой цифре речь?',
    answer: 'seven',
    options: ['three', 'five', 'seven', 'nine'],
    explain: 'seven',
    id: 80,
  },
  'Riddle-81': {
    riddle: 'What word is pronounced the same if you take away four of its five letters?',
    translate: 'Какое слово произносится одинаково, если убрать четыре из пяти его букв?',
    answer: 'queue',
    options: ['quake', 'queue', 'quart', 'quay'],
    explain: 'kjuː',
    id: 81,
  },
  'Riddle-82': {
    riddle: 'What word in the English language does the following: The first two letters signify a male, the first three letters signify a female, the first four letters signify a great, while the entire world signifies a great woman. What is the word?',
    translate: 'Какое слово в английском языке означает следующее: первые две буквы обозначают мужчину, первые три буквы обозначают женщину, первые четыре буквы означают великое, а весь мир обозначает великую женщину. Что за слово?',
    answer: 'heroine',
    options: ['heroine', 'heroes', 'Hermes', 'hero'],
    explain: 'heroine',
    id: 82,
  },
  'Riddle-83': {
    riddle: 'I come in darkness, but fill the mind with light. I bring enlightenment to some, while gripping others in the hand of fear. With me it can be a journey of inexplicable joy and sorrow. What I will show you will often be unreachable. Journey with me and what you see may haunt you. Journey with me and you may never want to return home. Journey with me and you will never know when it will end. What am I?',
    translate: 'Я прихожу во тьму, но наполняю разум светом. Я несу просветление некоторым, а других держу в руках страха. Со мной это может быть путешествие необъяснимой радости и печали. То, что я покажу вам, часто будет недоступно. Путешествие со мной и то, что вы видите, может преследовать вас. Путешествуйте со мной, и вы никогда не захотите возвращаться домой. Путешествуйте со мной, и вы никогда не узнаете, когда это закончится. Что это?',
    answer: 'dream',
    options: ['dream', 'picture', 'stars', 'miracle'],
    explain: 'dream',
    id: 83,
  },
  'Riddle-84': {
    riddle: 'I am so simple, that I can only point yet. I guide men all over the world. What am I?',
    translate: 'Я настолько прост, что могу только указать. Направляю людей по всему миру.',
    answer: 'compass',
    options: ['magnet', 'railway', 'wind', 'compass'],
    explain: 'compass',
    id: 84,
  },
  'Riddle-85': {
    riddle: 'I am a riddle of six; my first three letters refer to an automobile; my last three letters refer to a household animal; my first four letters is a fish; my whole is found in your room. What am I?',
    translate: 'Я загадка шести букв; мои первые три буквы относятся к автомобилю; мои последние три письма относятся к домашнему животному; мои первые четыре буквы - рыба; целое слово - предмет, которых находится в твоей комнате. Что это?',
    answer: 'carpet',
    options: ['chevrolet', 'carpet', 'sofa', 'dodge'],
    explain: 'carpet',
    id: 85,
  },
  'Riddle-86': {
    riddle: 'If you look at the number on my face you won\'t find thirteen anyplace.',
    translate: 'Если вы посмотрите на число на моем лице, вы нигде не найдете тринадцать.',
    answer: 'clock',
    options: ['youth', 'ground', 'clock', 'mirrow'],
    explain: 'clock',
    id: 86,
  },
  'Riddle-87': {
    riddle: 'The more of this there is, the less you see. What is it?',
    translate: 'Чем больше этого вокруг тебя, тем меньше ты видишь. Что это?',
    answer: 'darkness',
    options: ['people', 'alcohol', 'darkness', 'socks'],
    explain: 'darkness',
    id: 87,
  },
  'Riddle-88': {
    riddle: 'First you see me in the grass dressed in yellow; next I am in dainty white, then I fly away. What am I?',
    translate: 'Сначала вы видите меня в траве, одетого в желтое; затем я в изящном белом, затем я улетаю. Что это?',
    answer: 'dandelion',
    options: ['rose', 'chamomile', 'gooseberry', 'dandelion'],
    explain: 'dandelion',
    id: 88,
  },
  'Riddle-89': {
    riddle: 'I touch your face, I\'m in your words,  I\'m lack of space and beloved by birds.',
    translate: 'Я касаюсь твоего лица, я в твоих словах, мне тесно в пространстве и я любим птицами.',
    answer: 'air',
    options: ['water', 'air', 'ground', 'fire'],
    explain: 'air',
    id: 89,
  },
  'Riddle-90': {
    riddle: 'I have lakes with no water, mountains with no stone and cities with no buildings. What am I?',
    translate: 'У меня есть озера без воды, горы без камня и города без зданий. Что это?',
    answer: 'map',
    options: ['anthill', 'map', 'Moon', 'Mars'],
    explain: 'map',
    id: 90,
  },
};

const ALL_RIDDLES = [RIDDLES_1, RIDDLES_2, RIDDLES_3, RIDDLES_4, RIDDLES_5, RIDDLES_6];
export default ALL_RIDDLES;
