const RIDDLES_1 = {
  'Riddle-1': {
    riddle: 'Mr. and Mrs. Doe have six daughters and each daughter has one brother. How many people are in the Doe family?',
    translate: 'У мистера и миссис Доу есть шесть дочерей, и у каждой дочери есть один брат. Сколько человек в семье Доу?',
    answer: 'nine',
    options: ['fourteen', 'nine', 'twelve', 'eight'],
    explain: 'There are nine Mustards in the family. Since each daughter shares the same brother, there are six girls, one boy and Mr. and Mrs. Mustard.',
    id: 1,
  },
  'Riddle-2': {
    riddle: 'Who is that with a neck and no head, two arms and no hands?  What is it?',
    translate: 'C шеей и без головы, с двумя плечами и без рук? Что это?',
    answer: 'shirt',
    options: ['scarecrow', 'stick', 'tree', 'shirt'],
    explain: 'shirt',
    id: 2,
  },
  'Riddle-3': {
    riddle: 'If eleven plus two equals one, what does nine plus five equal?',
    translate: 'Если одиннадцать плюс два равно единица, то чему равняется девять плюс пять?',
    answer: 'two',
    options: ['three', 'fourteen', 'two', 'four'],
    explain: '11 o\'clock plus 2 hours = 1 o\'clock. 9 o\'clock plus 5 hours = 2 o\'clock',
    id: 3,
  },
  'Riddle-4': {
    riddle: 'What common English verb becomes its own past tense by rearranging its letters?',
    translate: 'Какой неправильный английский глагол становится собственным прошедшим временем при перестановке букв?',
    answer: 'eat',
    options: ['read', 'hold', 'beat', 'eat'],
    explain: 'eat -> ate',
    id: 4,
  },
  'Riddle-5': {
    riddle: 'The more you take, the more you leave behind. What am I?',
    translate: 'Чем больше вы сделаете, тем больше останется позади вас. Что это?',
    answer: 'footsteps',
    options: ['footsteps', 'experience', 'time', 'work'],
    explain: 'footsteps',
    id: 5,
  },
  'Riddle-6': {
    riddle: 'David\'s father has three sons: Snap, Crackle, and _____?',
    translate: 'У отца Дэвида трое сыновей: Снайп, Крэкл и _____?',
    answer: 'David',
    options: ['Carl', 'David', 'Snap', 'Crackle'],
    explain: 'David',
    id: 6,
  },
  'Riddle-7': {
    riddle: 'What belongs to you, but other people use it more than you?',
    translate: 'Что принадлежит вам, но окружающие люди используют это чаще вас?',
    answer: 'name',
    options: ['name', 'kindness', 'pen', 'car'],
    explain: 'name',
    id: 7,
  },
  'Riddle-8': {
    riddle: 'I am not alive, but I grow; I don\'t have lungs, but I need air; I don\'t have a mouth, but water kills me. What am I?',
    translate: 'Я не живой, но я расту; У меня нет легких, но мне нужен воздух; У меня нет рта, но вода убивает меня. Что это?',
    answer: 'fire',
    options: ['ghost', 'lightning', 'dark', 'fire'],
    explain: 'fire',
    id: 8,
  },
  'Riddle-9': {
    riddle: 'What can you break, even if you never pick it up or touch it?',
    translate: 'Что вы можете разрушить, без прикосновений к чему-либо или взаимодействий с кем-либо?',
    answer: 'promise',
    options: ['air', 'smile', 'promise', 'building'],
    explain: 'promise',
    id: 9,
  },
  'Riddle-10': {
    riddle: 'I make two people out of one. What am I?',
    translate: 'Я делаю двух человек из одного. Что я?',
    answer: 'mirror',
    options: ['mirror', 'physics', 'science', 'magic'],
    explain: 'mirror',
    id: 10,
  },
  'Riddle-11': {
    riddle: 'They have not flesh, nor feathers, nor scales, nor bone. Yet they have fingers and thumbs of their own. What are they?',
    translate: 'У них нет ни плоти, ни перьев, ни чешуи, ни костей. И все же у них есть свои пальцы. Что это?',
    answer: 'gloves',
    options: ['frogs', 'shoes', 'cold', 'gloves'],
    explain: 'gloves',
    id: 11,
  },
  'Riddle-12': {
    riddle: `Always in you, Sometimes on you;
    If I surround you, I can kill you.
    What am I?`,
    translate: 'Всегда в тебе, иногда на тебе. Eсли погрузишься в неё с головой, то можешь этого не пережить. Что это?',
    answer: 'water',
    options: ['bacteria', 'ground', 'love', 'water'],
    explain: 'water',
    id: 12,
  },
  'Riddle-13': {
    riddle: 'I have no feet, no hands, no wings, but I climb to the sky. What am I?',
    translate: 'У меня нет ни ног, ни рук, ни крыльев, но я поднимаюсь в небо. Что это?',
    answer: 'smoke',
    options: ['bird', 'smoke', 'rain', 'fog'],
    explain: 'smoke',
    id: 13,
  },
  'Riddle-14': {
    riddle: 'What goes up but never comes down?',
    translate: 'Что всегда увеличивается, но никогда не уменьшится?',
    answer: 'age',
    options: ['salary', 'experience', 'speed of light', 'age'],
    explain: 'age',
    id: 14,
  },
  'Riddle-15': {
    riddle: 'If you have me, you want to share me. If you share me, you haven\'t got me. What am I?',
    translate: 'Если у вас есть это, вы хотите поделиться этим. Если вы поделитесь этим, вы навсегда это потеряете. Что это?',
    answer: 'secret',
    options: ['secret', 'cigarettes', 'money', 'advice'],
    explain: 'secret',
    id: 15,
  },
};

const RIDDLES_2 = {
  'Riddle-16': {
    riddle: 'I shave every day, but my beard stays the same. What am I?',
    translate: 'Если у вас есть это, вы хотите поделиться этим. Если вы поделитесь этим, вы навсегда это потеряете. Что это?',
    answer: 'barber',
    options: ['pirate', 'soldier', 'grandfather', 'barber'],
    explain: 'barber',
    id: 16,
  },
  'Riddle-17': {
    riddle: 'I am a riddle of six; my first three letters refer to an automobile; my last three letters refer to a household animal; my first four letters is a fish; my whole is found in your room. What am I?',
    translate: 'Я загадка шести букв; мои первые три буквы относятся к автомобилю; мои последние три письма относятся к домашнему животному; мои первые четыре буквы - рыба; целое слово - предмет, которых находится в твоей комнате. Что это?',
    answer: 'carpet',
    options: ['chevrolet', 'carpet', 'sofa', 'dodge'],
    explain: 'carpet',
    id: 17,
  },
  'Riddle-18': {
    riddle: 'I\'m as small as an ant, as big as a whale. I\'ll approach like a breeze, but can come like a gale. By some I get hit, but all have shown fear. I\'ll dance to the music, though I can\'t hear. Of names I have many, of names I have one. I\'m as slow as a snail, but from me you can\'t run. What am I?',
    translate: 'Бываю такой же маленькой, как муравей, бываю такой же большой, как кит. Я подкрадусь медленно, как шлить, но могу появиться молниеносно, как шторм. От некоторых я получаю удары, но многим внушала страх. Я буду танцевать под музыку, хотя ничего не слышу слышу. Много имён, но суть одна. Я медленна, как улитка, но от меня ты не сможешь убежать. Что это?',
    answer: 'shadow',
    options: ['fear', 'wind', 'sprinter', 'shadow'],
    explain: 'shadow',
    id: 18,
  },
  'Riddle-20': {
    riddle: 'There is an ancient invention, still used in some parts of the world today, that allows people to see through walls. What is it?',
    translate: 'Древнее изобретение, которое позволяет людям видеть сквозь стены. Используется в некоторых частях мира до сих пор. Что это?',
    answer: 'window',
    options: ['magic', 'hammer', 'window', 'superglasses'],
    explain: 'window',
    id: 20,
  },
  'Riddle-21': {
    riddle: 'What is always in front of you but can’t be seen?',
    translate: 'Что всегда перед тобой, но не видно?',
    answer: 'future',
    options: ['happiness', 'future', 'lie', 'nose'],
    explain: 'future',
    id: 21,
  },
  'Riddle-22': {
    riddle: 'You walk into a room that contains a match, a kerosene lamp, a candle and a fireplace. What would you light first?',
    translate: 'Вы входите в комнату, в которой есть спичка, керосиновая лампа, свеча и камин. Что бы вы зажгли в первую очередь?',
    answer: 'match',
    options: ['lamp', 'fireplace', 'match', 'candle'],
    explain: 'match',
    id: 22,
  },
  'Riddle-23': {
    riddle: 'What can’t talk but will reply when spoken to?',
    translate: 'Что не может говорить, но ответит, когда с ним разговаривают?',
    answer: 'echo',
    options: ['echo', 'ghost', 'carrot', 'wind'],
    explain: 'echo',
    id: 23,
  },
  'Riddle-24': {
    riddle: 'The more of this there is, the less you see. What is it?',
    translate: 'Чем больше этого вокруг тебя, тем меньше ты видишь. Что это?',
    answer: 'darkness',
    options: ['people', 'alcohol', 'darkness', 'socks'],
    explain: 'darkness',
    id: 24,
  },
  'Riddle-25': {
    riddle: 'I’m light as a feather, yet the strongest person can’t hold me for ten minutes. What am I?',
    translate: 'Я легок, как перышко, но самый сильный человек не может удержать меня десять минут. Что я?',
    answer: 'breath',
    options: ['feather', 'breath', 'mouse', 'fly'],
    explain: 'breath',
    id: 25,
  },
  'Riddle-26': {
    riddle: 'What has many needles, but doesn’t sew?',
    translate: 'У чего много иголок, но не шьет?',
    answer: 'cactus',
    options: ['cactus', 'sewing machine', 'cold', 'tailor'],
    explain: 'cactus',
    id: 26,
  },
  'Riddle-27': {
    riddle: 'What has many teeth, but can’t bite?',
    translate: 'У чего много зубов, но не кусается?',
    answer: 'comb',
    options: ['shark', 'human', 'comb', 'spider'],
    explain: 'comb',
    id: 27,
  },
  'Riddle-28': {
    riddle: 'I am an odd number. Take away a letter and I become even. What number am I?',
    translate: 'Я нечётная цифра. Уберите одну букву и эта цифра станет чётной. О какой цифре речь?',
    answer: 'seven',
    options: ['three', 'five', 'seven', 'nine'],
    explain: 'seven',
    id: 28,
  },
  'Riddle-29': {
    riddle: 'Mary has four daughters, and each of her daughters has a brother. How many children does Mary have?',
    translate: 'У Марии четыре дочери, и у каждой из ее дочерей есть брат. Сколько детей у Мэри?',
    answer: 'five',
    options: ['eight', 'four', 'five', 'six'],
    explain: 'Five — each daughter has the same brother.',
    id: 29,
  },
  'Riddle-30': {
    riddle: 'What five-letter word becomes shorter when you add two letters to it?',
    translate: 'Какое пятибуквенное слово становится короче, когда вы добавляете к нему две буквы?',
    answer: 'short',
    options: ['early', 'earlier', 'shorter', 'short'],
    explain: 'short',
    id: 30,
  },
};

const RIDDLES_3 = {
  'Riddle-31': {
    riddle: 'What 4-letter word can be written forward, backward or upside down, and can still be read from left to right?',
    translate: 'Какое 4-буквенное слово может быть написано вперед, назад или вверх ногами, и все еще может читаться слева направо?',
    answer: 'NONE',
    options: ['HOME', 'ROME', 'NOON', 'BONE'],
    explain: 'NONE',
    id: 31,
  },
  'Riddle-32': {
    riddle: 'What is 3/7 chicken, 2/3 cat and 2/4 goat?',
    translate: 'Что получится из 3/7 курицы, 2/3 кошки и 2/4 козы?',
    answer: 'Chicago',
    options: ['Chicago', 'Michigan', 'China', 'Chicagao'],
    explain: 'Rebus',
    id: 32,
  },
  'Riddle-33': {
    riddle: 'What word is pronounced the same if you take away four of its five letters?',
    translate: 'Какое слово произносится одинаково, если убрать четыре из пяти его букв?',
    answer: 'queue',
    options: ['quake', 'queue', 'quart', 'quay'],
    explain: 'kjuː',
    id: 33,
  },
  'Riddle-34': {
    riddle: 'What word in the English language does the following: The first two letters signify a male, the first three letters signify a female, the first four letters signify a great, while the entire world signifies a great woman. What is the word?',
    translate: 'Какое слово в английском языке означает следующее: первые две буквы обозначают мужчину, первые три буквы обозначают женщину, первые четыре буквы означают великое, а весь мир обозначает великую женщину. Что за слово?',
    answer: 'heroine',
    options: ['heroine', 'heroes', 'hermes', 'heroin'],
    explain: 'heroine',
    id: 34,
  },
  'Riddle-35': {
    riddle: 'What can fill a room but takes up no space?',
    translate: 'Что может заполнить комнату, но не занимает места?',
    answer: 'light',
    options: ['furniture', 'people', 'things', 'light'],
    explain: 'light',
    id: 35,
  },
  'Riddle-36': {
    riddle: 'If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?',
    translate: 'Если ты уронишь меня, я обязательно сломаюсь, но дай мне улыбку, и я всегда буду улыбаться в ответ. Что это?',
    answer: 'mirror',
    options: ['bush', 'mirror', 'brush', 'cup'],
    explain: 'mirror',
    id: 36,
  },
  'Riddle-37': {
    riddle: 'What goes through cities and fields, but never moves?',
    translate: 'Что проходит через города и поля, но никогда не движется?',
    answer: 'road',
    options: ['mouse', 'car', 'bird', 'road'],
    explain: 'road',
    id: 37,
  },
  'Riddle-38': {
    riddle: 'I have lakes with no water, mountains with no stone and cities with no buildings. What am I?',
    translate: 'У меня есть озера без воды, горы без камня и города без зданий. Что это?',
    answer: 'map',
    options: ['anthill', 'map', 'Moon', 'Mars'],
    explain: 'map',
    id: 38,
  },
  'Riddle-39': {
    riddle: 'What has a neck but no head?',
    translate: 'У чего есть шея, но нет головы?',
    answer: 'bottle',
    options: ['bottle', 'ghost', 'tree', 'dove'],
    explain: 'bottle',
    id: 39,
  },
  'Riddle-40': {
    riddle: 'I do not have wings, but I can fly. I don’t have eyes, but I can cry. What am I?',
    translate: 'У меня нет крыльев, но я умею летать. У меня нет глаз, но я могу плакать. Что это?',
    answer: 'cloud',
    options: ['cloud', 'fog', 'ground', 'ocean'],
    explain: 'cloud',
    id: 40,
  },
  'Riddle-41': {
    riddle: 'People buy me to eat, but never eat me. What am I?',
    translate: 'Люди покупают меня, чтобы поесть, но никогда не едят меня. Что я?',
    answer: 'plate',
    options: ['vegetables', 'soap', 'plate', 'candy'],
    explain: 'plate',
    id: 41,
  },
  'Riddle-42': {
    riddle: 'You will throw me away when you want to use me. You will take me in when you don’t want to use me. What am I?',
    translate: 'Вы выбросите меня, когда захотите меня использовать. Вы заберёте меня обратно, когда я стану не нужен. Что это?',
    answer: 'anchor',
    options: ['rubbish', 'anchor', 'money', 'time'],
    explain: 'anchor',
    id: 42,
  },
  'Riddle-43': {
    riddle: 'I am so simple, that I can only point yet I guide men all over the world. What am I?',
    translate: 'Я настолько прост, что могу только указать, но направляю людей по всему миру.',
    answer: 'compass',
    options: ['magnet', 'railway', 'wind', 'compass'],
    explain: 'compass',
    id: 43,
  },
  'Riddle-44': {
    riddle: 'I come in darkness, but fill the mind with light. I bring enlightenment to some, while gripping others in the hand of fear. With me it can be a journey of inexplicable joy and sorrow. What I will show you will often be unreachable. Journey with me and what you see may haunt you. Journey with me and you may never want to return home. Journey with me and you will never know when it will end. What am I?',
    translate: 'Я прихожу во тьму, но наполняю разум светом. Я несу просветление некоторым, а других держу в руках страха. Со мной это может быть путешествие необъяснимой радости и печали. То, что я покажу вам, часто будет недоступно. Путешествие со мной и то, что вы видите, может преследовать вас. Путешествуйте со мной, и вы никогда не захотите возвращаться домой. Путешествуйте со мной, и вы никогда не узнаете, когда это закончится. Что это?',
    answer: 'dream',
    options: ['dream', 'picture', 'stars', 'miracle'],
    explain: 'dream',
    id: 44,
  },
  'Riddle-45': {
    riddle: 'I reflect the light, thats not very bright, I sit in the same place all year, all the time. Right here, you cannot see me all right, at least when its not night.',
    translate: 'Я отражаю свет, который не очень яркий, я сижу в одном и том же месте весь год, все время. Прямо здесь, вы не можете видеть меня хорошо, по крайней мере, если сейчас не ночь.',
    answer: 'Moon',
    options: ['Sun', 'Moon', 'light', 'mirror'],
    explain: 'Moon',
    id: 44,
  },
};

const RIDDLES_4 = {
  'Riddle-46': {
    riddle: 'I know a thousand faces, of many who have died. Wielding well a mighty power. Masses fall upon their knees, to scarce behold my only side.',
    translate: 'Я знаю тысячу лиц и многие уже мертвы. Обладаю могущественной силой. Массы падают на колени, чтобы едва увидеть мою единственную сторону.',
    answer: 'coin',
    options: ['photo', 'ground', 'money', 'coin'],
    explain: 'coin',
    id: 46,
  },
  'Riddle-47': {
    riddle: 'I am the outstretched fingers that seize and hold the wind. Wisdom flows from me in other hands. My merest touch brings laughter. What am I?',
    translate: 'Я - вытянутые пальцы, которые захватывают и удерживают ветер. Мудрость течет от меня в другие руки. Мое простое прикосновение приносит смех. Что это?',
    answer: 'feather',
    options: ['finger', 'pen', 'feather', 'hand'],
    explain: 'feather',
    id: 47,
  },
  'Riddle-48': {
    riddle: 'A house of wood in a hidden place. Built without nails or glue. High above the ground.',
    translate: 'Дом из дерева в скрытом месте. Построен без гвоздей и клея. Высоко над землей.',
    answer: 'nest',
    options: ['nest', 'tree', 'house', 'anthill'],
    explain: 'nest',
    id: 48,
  },
};

const RIDDLES_5 = {

};

const RIDDLES_6 = {

};

/* Different lights do make me strange, thus into different sizes I will change. What am I?
I am the pupil of an eye. */

/* My thunder comes before the lightning; My lightning comes before the clouds;
My rain dries all the land it touches. What am I?

A volcano. */

const ALL_RIDDLES = [RIDDLES_1, RIDDLES_2, RIDDLES_3, RIDDLES_4, RIDDLES_5, RIDDLES_6];
export default ALL_RIDDLES;
